---
title: "Interdisciplinary Team Project Specification and Assessment"
author: "Your Name"
date: today
date-format: long
number-sections: true
number-depth: 3
format:
  html:
    toc: true
    toc-location: right
    number-sections: true
    number-depth: 3
    html-math-method: katex
    embed-resources: true
# bibliography: dasc-6000.bib 
# csl: ieee-with-url.csl
# linkcolor: red
# urlcolor: blue
# link-citations: yes
# header-includes:
#   - \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

# Team Project Goal

The goal of this semester-long, interdisciplinary team project is apply your machine learning knowledge and skills learned in the course to solving a practical problem in a team setting.

# Team Size

Three people per team is the ideal size. Four is too many. For justifiable reasons, a team size of two is acceptable. Under extraordinary and justifiable circumstances, one can do the project in solo mode. When selecting team members, do not look for selfsame members from an academic perspective. Team members should complement each others' strengths, rather than duplicating them. For example, one team member has expertise in requirements gathering and specification, another thrives in writing code, and the third has special talent for testing the code and writing documentation.

# Problem Selection and Scope

Choose an ill-posed problem, which is ideally suited for solution using machine learning algorithms. If possible, select a problem from a domain that you are not familiar with. Begin with the following questions: What is the problem in the domain that you plan to solve. Why is it important to solve this problem? What are the costs and benefits to an organization by solving the problem? Do you have sufficient and right data for training the machine learning algorithms?

The project scope should commensurate with the team size. The team project is 20% of the course grade. If three people are on the team, the total project effort should be equal to 60% of the course effort.

# Deliverables

The following table is provided to plan various deliverables of the project.

| Deliverable	| Description	| Due Date	| 
|:--------------|:------------------------|:-----------:|
| Project Proposal |	Detailed plan including problem statement, team members and roles, solution approach, and work breakdown (who will do what). |	14 Oct 2024	| 
| Midterm Report |	Progress report, challenges, and next steps. | 28 Oct 2024	| 
| Final Codebase & Documentation	| Complete code, deployment scripts, and user/technical documentation. |	4 Dec 2024	|  
| Final Presentation & Demo	| 10- to 15-minute demo of working project with Q&A. |	2 Nov 2024, 2 Dec 2024	| 


# Assessment

| Criteria	| Description	| Weight |
|:------------------|:-------------------------|-------:|
| Technical Implementation |	Functionality, code quality, use of best practices, and design patterns. |	40% |
| Team Collaboration |	Contribution of team members, use of version control, communication, and project management tools. | 20% |
| Documentation	| Completeness and clarity of both user and technical documentation. |	 15% |
| Presentation & Demo	| Clarity of explanation, depth of understanding, and quality of the demo. |	15% |
| Creativity & Innovation |	Novelty and originality of the solution. |	10% |


# Submission

Please upload the following deliverables to Canvas, one submission per team:

1. Project proposal
1. Midterm report
1. Final codebase
1. Documentation

# Honor Code

Ensure that all work is original and properly attributed. Plagiarism or any form of cheating will result in a failing grade for the project. Collaboration within the team is encouraged, but sharing code or solutions with other teams is prohibited.
